AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
  - Name: DatadogServerless
    Parameters:
      stackName: !Ref "AWS::StackName"
      apiKeySecretArn: !Ref ApiKeySecretArn
      dotnetLayerVersion: "23" # dotnet lambda layer version
      extensionLayerVersion: "92" # datadog lambda layer version
      service: !Ref ServiceName
      env: !Ref Env
      version: !Ref CommitHash
      site: !Ref DDSite
      captureLambdaPayload: true
Description: Sample .NET 8 Lambda chain (caller -> worker)

Parameters:
  ServiceName:
    Type: String
    Default: CallerWorkerService
  Env:
    Type: String
    Default: dev
  CommitHash:
    Type: String
    Default: latest
  DDSite:
    Type: String
    Default: datadoghq.com
  ApiKeySecretArn:
    Type: String
    Default: ""

Globals:
  Function:
    Runtime: dotnet8
    Timeout: 10
    MemorySize: 256
    # Tracing: Active
    Architectures:
      - x86_64

Resources:
  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dd-prospects-worker
      CodeUri: src/WorkerFunction/
      Handler: WorkerFunction::WorkerFunction.Functions::Handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref ApiKeySecretArn
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      BuildMethod: dotnet8

  CallerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: dd-prospects-caller
      CodeUri: src/CallerFunction/
      Handler: CallerFunction::CallerFunction.Functions::Handler
      Environment:
        Variables:
          WORKER_FUNCTION_URL: !GetAtt WorkerFunctionUrl.FunctionUrl
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref ApiKeySecretArn
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      BuildMethod: dotnet8

Outputs:
  CallerFunctionName:
    Description: Lambda function name for the caller
    Value: !Ref CallerFunction
  WorkerFunctionName:
    Description: Lambda function name for the worker
    Value: !Ref WorkerFunction
  WorkerFunctionUrl:
    Description: Lambda function URL for the worker
    Value: !GetAtt WorkerFunctionUrl.FunctionUrl
  CallerFunctionUrl:
    Description: Lambda function URL for the caller
    Value: !GetAtt CallerFunctionUrl.FunctionUrl
